### ISSUE TITLE
Repository for Debian bullseye

### ISSUE THREAD

**Issue by gedia** [eLvErDe/hwraid#124]
It's that time of the year I guess :-).

It's a little early for release, but it would be handy if there were a bullseye repo for testing etc. Thank you for all your work!

**Comment by eLvErDe** [comment]
Agreed :(
But I need to fix everything for Python3, that's a bit of work sadly

**Comment by xtaran** [comment]
> But I need to fix everything for Python3, that's a bit of work sadly

Yes and no.

For me it currently suffices to use the HWRaid buster repo packages on bullseye and installing the `python-is-python2` package. This would also be a temporary solution for a HWRaid bullseye repo until the Python 3 conversion is ready.

Actually still having to use the buster repo for bullseye causes more headaches for me in Ansible than I have issues with installing  `python-is-python2` for now because of some of the packages not being python3-ready. So please provide a bullseye repo even if the Python 3 migration isn't through. 

Thanks in advance!

**Comment by kralge** [comment]
I have been using buster packages (`megactl` and `megaraid-status`) for years on bullseye with `python-is-python2` package installed for Python2.

Now it looks I will have to get rid of Python2 because of other compatibility issues. For me only `megaraid-status` package needs Python2, so I checked and found that only replacing `print ''` to `print('')` makes megaraid-status to run by python3 seemingly without an issue.

So I would be very happy if only `megaraid-status` could be replaced with a new version supporting Python3.

**Comment by eengstrom** [comment]
FWIW, Not just `bullseye` but also support for Ubuntu Focal and Hirsute.  

From @kralge's comments, getting rid of the `python2` requirement seems simple on the surface.  There is also a PR for this (#106).  

Looking for more feedback from @eLvErDe, and even offering to help if assistance is needed.

**Comment by eLvErDe** [comment]
Hello,

It's on my list it will done before bullseye release or shortly after because I'll need it anyway.
For the moment you can of course use buster repository and install python-is-python2.
I'll try to work on it this weekend, but it's not like "just merging a few PR", first I need to evaluate all PR and merge them, then I'll merge python3 repository, then I need to hack debian package to handle python2/python3 in a clean way (I think detecting primary version at built time by looking at python virtual package and then passing the real package name as runtime dependency using substvar should work) and finally I need to rebuild all packages for all supported distributions (and I don't really remember if I made proper tooling for that so I may need to rewrite this).
So yes it'll be done, but no it's not a matter of minutes ;-)

Regards, Adam.

**Comment by eengstrom** [comment]
Adam (@eLvErDe) - thanks - I know that it's not trivial, and yet I made it sound like it was.  Sorry. 

Sadly, using `python-is-python2` is not an option for us, especially on our newer Ubuntu (>= 20) systems that finally have switched everything "standard" to `python3`

If you need help, esp. on the Ubuntu side, please let me know.

**Comment by gedia** [comment]
I've also quickly hacked `megaclisas-status` to work with python3. I've created a gist of my version in case it is be useful to anyone:

https://gist.github.com/gedia/80cf0881d9c96c0efdacd37f4f83408c

**Comment by stephen-smith** [comment]
Thanks for the efforts!  Bullseye is now stable, any ETA on the bullseye repo?

**Comment by eLvErDe** [comment]
Hello,

I published bullseye and focal repositories, but there's only megali/megaclisas-status package for the moment.

Regards, Adam.

**Comment by xtaran** [comment]
This can be closed now, but the Bookworm repo is still missing, see #139. ;-)
